apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blazor-workshop
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: blazor-workshop
  path: ../../infrastructure/blazor-workshop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: flux-system
