apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blazor-workshop
  namespace: blazor-workshop
spec:
  releaseName: blazor-workshop
  interval: 1m
  chart:
    spec:
      chart: ../charts/blazor-workshop-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    frontend:
      image: "nginxdemos/hello"
      replicaCount: 1
      sentryDsn: ""
    backend:
      image: "nginxdemos/hello"
      replicaCount: 1
    ingress:
      enabled: true
      hostname: "candidate-name.maxtld.dev"

